### create
POST localhost:8080/api/tinyUrl
Content-Type: application/json

{
  "url": "https://instagram.com"
}

### update
PATCH localhost:8080/api/tinyUrl
Content-Type: application/json

{
  "id": "a115979f-e9fd-478e-997c-19cbedb36ef3",
  "url": "https://facebook.com"
}

### delete
DELETE localhost:8080/api/tinyUrl/eeb28744-936d-4fe6-b5a5-8cbe5340de8a
