### create
POST localhost:8080/api/tinyUrl
Content-Type: application/json

{
  "url": "https://instagram.com"
}

### update
PATCH localhost:8080/api/tinyUrl
Content-Type: application/json

{
  "id": "abd1af39-5c00-4e8e-a16c-bf2f8fe8195a",
  "url": "https://facebook.com"
}

### delete
DELETE localhost:8080/api/tinyUrl/abd1af39-5c00-4e8e-a16c-bf2f8fe8195a
